mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mappers/**/*.xml
query:
  max:
#    #最大的分页数
    limit: 1000

spring:
  aop:
  #日志拦截
    auto: true
    proxy-target-class: false
  i18n:
    default:
      locale:
        language_country: zh_CN
  messages:
    #国际化配置
    basename: i18n/msg
    encoding: UTF-8
    param_name: lang
  profiles:
    active: prod